app/models/chamado.py
from app import db
from datetime import datetime

class Chamado(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titulo = db.Column(db.String(100), nullable=False)
    descricao = db.Column(db.Text, nullable=False)
    status = db.Column(db.String(50), default='aberto')
    data_criacao = db.Column(db.DateTime, default=datetime.utcnow)
    usuario_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/models/user.py
from app import db
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(150), nullable=False)
    role = db.Column(db.String(50))

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)
    app.config.from_object('app.config.Config')

    db.init_app(app)
    login_manager.init_app(app)

    from app.controllers import auth_controller, chamado_controller,user_controller
    app.register_blueprint(auth_controller.bp)
    app.register_blueprint(chamado_controller.bp)
    app.register_blueprint(user_controller.bp)


    return app

app/controllers/auth_controller.py
from flask import Blueprint, render_template, redirect, request, flash, url_for
from app.models.user import User
from app import db, login_manager
from flask_login import login_user, logout_user

bp = Blueprint('auth', __name__)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@bp.route('/')
def root():

    # Redireciona automaticamente para a rota /login

    return redirect(url_for('auth.login'))

@bp.route('/login', methods=['GET', 'POST'])
def login():
    # Verifica se a tabela de usuários está vazia

    if User.query.count() == 0:
        
        # Se estiver vazia, cria o usuário admin
        admin_user = User.query.filter_by(username='admin').first()
        if not admin_user:
            new_admin = User(username='admin', password='admin123', role='admin')
            db.session.add(new_admin)
            db.session.commit()
            flash('Usuário admin criado automaticamente')

    if request.method == 'POST':
        user = User.query.filter_by(username=request.form['username']).first()
        if user and user.password == request.form['password']:
            login_user(user)
            return redirect('/dashboard')
        flash('Usuário ou senha inválidos')

    return render_template('login.html')

@bp.route('/logout')
def logout():
    logout_user()
    return redirect('/login')

app/controllers/chamado_controller.py
from flask import Blueprint, render_template, redirect, request
from flask_login import login_required, current_user
from app import db
from app.models.chamado import Chamado
from app.models.user import User


bp = Blueprint('chamado', __name__)

# Rota do dashboard

@bp.route('/dashboard')
@login_required
def dashboard():
    chamados = Chamado.query.all()
    return render_template('dashboard.html', chamados=chamados)

# Rota de criação de novo chamado

@bp.route('/chamado/novo', methods=['GET', 'POST'])
@login_required
def novo_chamado():
    if request.method == 'POST':
        chamado = Chamado(
            titulo=request.form['titulo'],
            descricao=request.form['descricao'],
            usuario_id=current_user.id
        )
        db.session.add(chamado)
        db.session.commit()
        return redirect('/dashboard')
    return render_template('chamados/novo.html')

# Rota de fechamento e exclusão de chamado; o front utiliza um script onde o controller é ativaddo.

@bp.route('/chamado/fechar/<int:id>', methods=['POST'])
@login_required
def fechar_chamado(id):
    chamado = Chamado.query.get(id)
    if chamado:
        chamado.status = 'fechado'
        db.session.commit()
    return redirect('/dashboard')

@bp.route('/chamado/excluir/<int:id>', methods=['POST'])
@login_required
def excluir_chamado(id):
    chamado = Chamado.query.get(id)
    if chamado:
        db.session.delete(chamado)
        db.session.commit()
    return redirect('/dashboard')

app/controllers/user_controller.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models.user import User
from flask_login import login_required, current_user
from app import db
import requests

def notificar_email(destinatario, assunto, mensagem):
    payload = {
        "to": destinatario,
        "subject": assunto,
        "message": mensagem
    }
    try:
        requests.post("http://localhost:5001/send-email", json=payload)
    except Exception as e:
        print("Erro ao enviar e-mail:", e)


bp = Blueprint('user', __name__)

# Rota de listagem de usuário

@bp.route('/listar')
@login_required
def listar_usuarios():
    usuarios = User.query.all()
    return render_template('listar.html', usuarios=usuarios)

# Rota de criação de usuário

@bp.route('/user/novo')
@login_required
def novo_usuario():
    return render_template('user/novo.html')

# Rota de envio de dados para o banco de usuário

@bp.route('/user/criar', methods=['POST'])
@login_required
def criar_usuario():
    username = request.form['username']
    password = request.form['password']
    role = request.form['role']

    novo = User(username=username, password=password, role=role)
    db.session.add(novo)
    db.session.commit()
    notificar_email(username, "Bem-vindo!", "Seu usuário foi criado com sucesso.")
    return redirect(url_for('user.listar_usuarios'))

# Rota de deleção de usuário

@bp.route('/user/deletar/<int:id>', methods=['POST'])
@login_required
def deletar_usuario(id):
    usuario = User.query.get(id)
    db.session.delete(usuario)
    db.session.commit()
    return redirect(url_for('user.listar_usuarios'))

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Sistema de Chamados</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

app/templates/chamados/novo.html
<!DOCTYPE html>
<html>
    <head>
        <title>abertura de chamado</title>
        <link rel="stylesheet" href="../../static/style.css">
        <script> return novoChamado </script>
    </head>
    <body>
        <h1>Novo Chamado</h1>
        <form id="formNovoChamado" method="post">
            <input id= "tituloNovoChamado" name="titulo" placeholder="Título">
            <textarea id="descricaoNovoChamado" name="descricao" placeholder="Descrição"></textarea>
            <button id="btn" type="submit">Criar</button>
        </form>
        <a href="/dashboard"><button id="btnCancel">cancelar</button></a> 
    </body>
</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Sistema de Chamados</title>
    <link rel="stylesheet" href="../static/style.css">
</head>
<body>
    <h1>Chamados</h1>

    <table>
        <tr>
            <th>ID</th>
            <th>TÍTULO</th>
            <th id="descTab">DESCRIÇÃO</th>
            <th>STATUS</th>
            <th>USUÁRIO</th>
            <th>AÇÃO</th>
        </tr>
        {% for chamado in chamados %}
        <tr>
            <td>{{ chamado.id }}</td>
            <td>{{ chamado.titulo }}</td>
            <td>{{ chamado.descricao }}</td>
            <td>{{ chamado.status }}</td>
            <td>{{ chamado.usuario_id }}</td>
            <td id="tabAction">
                <button id="btnDash" onclick="fecharChamado({{ chamado.id }})">fechar chamado</button>
                <button id="btnExclude" onclick="excluirChamado({{ chamado.id }})">excluir</button>
            </td>
        </tr>
        {% endfor %}
    </table>

    <div id="btnDiv">
        <a href="/chamado/novo">
            <button id="btnDash">Novo chamado</button> 
        </a>
        <a href="/listar">
            <button id="btnDash">Lista de Usuarios</button> 
        </a>
        <a href="/logout">
            <button id="btnCancel">Logout</button> 
        </a>
    </div>

    
    <script>
        function fecharChamado(id) {
            fetch(`/chamado/fechar/${id}`, { method: 'POST' })
                .then(() => location.reload());
        }
    
        function excluirChamado(id) {
            fetch(`/chamado/excluir/${id}`, { method: 'POST' })
                .then(() => location.reload());
        }
    </script>
    
</body>
</html>

app/templates/listar.html
<!DOCTYPE html>
<html>
  <head>
      <title>Sistema de Chamados</title>
      <link rel="stylesheet" href="../static/style.css">
  </head>
  <body>

    <h1>Usuários</h1>

    <!-- tabela de usuários -->
     
    <table>
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Role</th>
        <th>Ações</th>
      </tr>
    
      {% for u in usuarios %}
      <tr>
        <td>{{ u.id }}</td>
        <td>{{ u.username }}</td>
        <td>{{ u.role }}</td>
        <td id="tabAction">
          <form action="{{ url_for('user.deletar_usuario', id=u.id) }}" method="post" style="display:inline;">
            <button id="btnExclude" type="submit">Excluir</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </table>

    <!-- Botão para adicionar novo usuário -->
    <a href="/user/novo">
      <button id="btn" type="button">Novo Usuário</button>
    </a>

    <!-- Link para voltar à lista -->
    <a href="/dashboard">
      <button id="btnCancel" type="button">voltar</button>
    </a>

  </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Sistema de Chamados</title>
    <link rel="stylesheet" href="../static/style.css">
</head>
<body>
    <h1>Login</h1>
    <form id="formLogin" method="post">
        <input id="inputLogin" name="username" placeholder="Usuário">
        <input id="inputLogin" name="password" placeholder="Senha" type="password">
        <button id="btn" type="submit">Entrar</button>
    </form>
</body>
</html>

app/templates/user/novo.html
<!DOCTYPE html>
<html>
	<head>
		<title>Sistema de Chamados</title>
		<link rel="stylesheet" href="../static/style.css">
	</head>

	<h1>Novo Usuário</h1>

	<form id="formLogin" action="{{ url_for('user.criar_usuario') }}" method="post">
		<input id="inputLogin" type="text" name="username" placeholder="Usuário">
		<input id="inputLogin" type="password" name="password" placeholder="Senha">

		<select id="selectuser" name="role" placeholder="Cargo">
			<option value="admin">Admin</option>
			<option value="tecnico">Técnico</option>
			<option value="cliente">Cliente</option>
		</select>
		<button id="btn" type="submit">Criar</button>
	</form>

	<a href="/dashboard"><button id="btnCancel">cancelar</button></a>
</html>